name: Development
on:
  push:
    branches:
    - develop
  pull_request:
    branches:
    - develop
    types:
    - closed
jobs:
  build:
    name: Build
    uses: bayudwiyansatria/.github/.github/workflows/build-java-maven.yaml@master
    with:
      JAVA_VERSION: 11
    secrets:
      MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
      MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
  deploy:
    name: Deploy
    uses: bayudwiyansatria/.github/.github/workflows/deploy-maven.yaml@master
    needs: build
    with:
      JAVA_VERSION: 11
      ENVIRONMENT: development
    secrets:
      MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
      MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
