name: Features
on:
  push:
    branches:
    - feature/**
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        java-version: [ 11.0.3 ]
        operating-system: [ ubuntu-latest ]
    steps:
    - name: Prepare
      uses: actions/checkout@v2
    - name: Set Up Java Development Kit
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.java-version }}
        distribution: adopt
        cache: maven
        server-id: github
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
    - name: Maven clean test package
      run: |
        mvn clean
        mvn test
        mvn package --file pom.xml
      env:
        MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
