name: Main
on:
  workflow_dispatch:
    inputs:
      major-version:
        description: 'Major Version'
        required: true
        default: '1'
      minor-version:
        description: 'Minor Version'
        required: true
        default: '0'
      incremental-version:
        description: 'Incremental Version'
        required: true
        default: '0'
jobs:
  build:
    name: Build
    uses: bayudwiyansatria/.github/.github/workflows/build-java-maven.yaml@master
    with:
      JAVA_VERSION: 11
    secrets:
      MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
      MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
  deploy:
    name: Deploy
    uses: bayudwiyansatria/.github/.github/workflows/relase-maven.yaml@master
    needs: build
    with:
      JAVA_VERSION: 11
      MAJOR_VERSION: ${{ github.event.inputs.major-version }}
      MINOR_VERSION: ${{ github.event.inputs.minor-version }}
      INCREMENTAL_VERSION: ${{ github.event.inputs.incremental-version }}
    secrets:
      MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
      MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
